### ISSUE TITLE
EPUB exports for all posts

### ISSUE THREAD

**Issue by nullishamy** [nullishamy/nullishamy.github.io#4]
Would be nice to be able to export the posts as EPUB, for better accessibility, and convenient offline reading.

**Comment by nullishamy** [comment]
https://pandoc.org/MANUAL.html#epubs

**Comment by nullishamy** [comment]
pandoc -o fedi.epub src/content/into-the-fediverse.md --metadata-file meta.yml
```yml
title:
  - type: main
    text: 'into the fediverse'
creator:
- role: author
  text: nullishamy
publisher: nullishamy
abstract: 'my journey on the fediverse, and my summary after a few months of use'
rights: © 2024 nullishamy
```
